/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_shbtwebgpuengine_free(a: number): void;
export function shbtwebgpuengine_capture_frame_rgba(a: number, b: number): number;
export function shbtwebgpuengine_create(a: number, b: number): number;
export function shbtwebgpuengine_debug_eparams(a: number, b: number): void;
export function shbtwebgpuengine_get_active_observers_count(a: number): number;
export function shbtwebgpuengine_hud_json(a: number, b: number): void;
export function shbtwebgpuengine_particle_count(a: number): number;
export function shbtwebgpuengine_set_channels(a: number, b: number, c: number): void;
export function shbtwebgpuengine_set_dark_glow(a: number, b: number): void;
export function shbtwebgpuengine_set_dispersion(a: number, b: number): void;
export function shbtwebgpuengine_set_doppler_enabled(a: number, b: number): void;
export function shbtwebgpuengine_set_glitch_enabled(a: number, b: number): void;
export function shbtwebgpuengine_set_glitch_intensity(a: number, b: number): void;
export function shbtwebgpuengine_set_lensing_enabled(a: number, b: number): void;
export function shbtwebgpuengine_set_lensing_scale(a: number, b: number): void;
export function shbtwebgpuengine_set_playing(a: number, b: number): void;
export function shbtwebgpuengine_set_projection(a: number, b: number): void;
export function shbtwebgpuengine_set_redshift(a: number, b: number): void;
export function shbtwebgpuengine_set_simulation_controls(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function shbtwebgpuengine_set_speed(a: number, b: number): void;
export function shbtwebgpuengine_set_unwrap_transition(a: number, b: number): void;
export function shbtwebgpuengine_set_viewport_mode(a: number, b: number): void;
export function shbtwebgpuengine_step_frame(a: number, b: number, c: number): void;
export function shbtwebgpuengine_unproject_and_dispatch_causal_point(a: number, b: number, c: number, d: number, e: number): number;
export function shbtwebgpuengine_update_frame_telemetry(a: number, b: number, c: number, d: number): void;
export function __wbg_wasmshbtengine_free(a: number): void;
export function wasmshbtengine_causal_point_count(a: number): number;
export function wasmshbtengine_get_causal_point_buffer_byte_len(a: number): number;
export function wasmshbtengine_get_causal_point_buffer_ptr(a: number): number;
export function wasmshbtengine_get_hud_telemetry_json(a: number, b: number): void;
export function wasmshbtengine_get_particle_buffer_byte_len(a: number): number;
export function wasmshbtengine_get_particle_buffer_ptr(a: number): number;
export function wasmshbtengine_get_seed_buffer_byte_len(a: number): number;
export function wasmshbtengine_get_seed_buffer_ptr(a: number): number;
export function wasmshbtengine_new(a: number, b: number, c: number): number;
export function wasmshbtengine_particle_count(a: number): number;
export function wasmshbtengine_seed_count(a: number): number;
export function wasmshbtengine_update_epoch(a: number, b: number): void;
export function __wbg_get_visualizertelemetry_active_caustics(a: number): number;
export function __wbg_get_visualizertelemetry_max_einstein_radius(a: number): number;
export function __wbg_get_visualizertelemetry_peak_convergence(a: number): number;
export function __wbg_get_visualizertelemetry_peak_shear(a: number): number;
export function __wbg_set_visualizertelemetry_active_caustics(a: number, b: number): void;
export function __wbg_set_visualizertelemetry_max_einstein_radius(a: number, b: number): void;
export function __wbg_set_visualizertelemetry_peak_convergence(a: number, b: number): void;
export function __wbg_set_visualizertelemetry_peak_shear(a: number, b: number): void;
export function __wbg_visualizerengine_free(a: number): void;
export function __wbg_visualizertelemetry_free(a: number): void;
export function visualizerengine_clear_seeds(a: number): void;
export function visualizerengine_get_seeds_ptr(a: number): number;
export function visualizerengine_get_uniform_ptr(a: number): number;
export function visualizerengine_is_dirty(a: number): number;
export function visualizerengine_new(a: number, b: number): number;
export function visualizerengine_register_seed(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function visualizerengine_set_dark_glow(a: number, b: number): void;
export function visualizerengine_set_dispersion(a: number, b: number): void;
export function visualizerengine_set_doppler_enabled(a: number, b: number): void;
export function visualizerengine_set_lensing_enabled(a: number, b: number): void;
export function visualizerengine_set_lensing_scale(a: number, b: number): void;
export function visualizerengine_telemetry(a: number): number;
export function visualizerengine_update_camera_matrices(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function visualizerengine_update_telemetry(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core_608f92abc48d28da___ops__function__FnMut_______Output______as_wasm_bindgen_c04f4cf843a15bdf___closure__WasmClosure___describe__invoke___wgpu_a1de0f0a97155907___backend__webgpu__webgpu_sys__gen_GpuUncapturedErrorEvent__GpuUncapturedErrorEvent_____(a: number, b: number, c: number): void;
export function _dyn_core_608f92abc48d28da___ops__function__FnMut_______Output______as_wasm_bindgen_c04f4cf843a15bdf___closure__WasmClosure___describe__invoke___wasm_bindgen_c04f4cf843a15bdf___JsValue_____(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen_c04f4cf843a15bdf___convert__closures__invoke2_mut___wasm_bindgen_c04f4cf843a15bdf___JsValue__wasm_bindgen_c04f4cf843a15bdf___JsValue_____(a: number, b: number, c: number, d: number): void;
